name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'
permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'There has not been any recent activity on this ticket, so we are marking it as stale. Please comment if you have any additional questions.'
          days-before-issue-stale: 14
          days-before-pr-stale: -1
          days-before-close: 1
          close-issue-message: 'There has not been any recent activity on this ticket, so we are resolving it. Thanks for reaching out!'
          only-issue-labels: 'waiting-for-reporter'
